import { Expediente, Requirente, Usuario } from './types';

export const mockRequirentes: Requirente[] = [
  {
    id: 'req-1',
    nombre: 'UPCN - Unión Personal Civil de la Nación',
    tipo: 'SINDICATO',
    cuit: '30-54398549-4',
    domicilio: 'Córdoba 965, C.A.B.A.',
  },
  {
    id: 'req-2',
    nombre: 'OSDE - Obra Social de Empresarios y Directivos',
    tipo: 'OBRA_SOCIAL',
    cuit: '30-54398232-1',
    domicilio: 'Leandro N. Alem 1067, C.A.B.A.',
  },
  {
    id: 'req-3',
    nombre: 'SMATA - Sindicato de Mecánicos y Afines',
    tipo: 'SINDICATO',
    cuit: '30-54876543-2',
    domicilio: 'Av. Belgrano 665, C.A.B.A.',
  },
];

export const mockInspectores: Usuario[] = [
  { id: 'usr-1', nombre: 'Carlos', apellido: 'Rodríguez', rol: 'INSPECTOR', email: 'c.rodriguez@sigef.gob.ar' },
  { id: 'usr-2', nombre: 'María', apellido: 'González', rol: 'INSPECTOR', email: 'm.gonzalez@sigef.gob.ar' },
  { id: 'usr-3', nombre: 'Pablo', apellido: 'Fernández', rol: 'INSPECTOR', email: 'p.fernandez@sigef.gob.ar' },
];

export const mockExpedientes: Expediente[] = [
  {
    id: 'exp-001',
    numeroExpediente: 'SIGEF-2026-00001',
    caratula: 'UPCN c/ TECNOLOGÍAS DEL SUR S.A. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'TECNOLOGÍAS DEL SUR S.A.',
      cuit: '30-71234567-8',
      domicilio: 'Av. Corrientes 1234, C.A.B.A.',
      actividadPrincipal: 'Desarrollo de Software',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'C_DETERMINACION',
    fechaInicio: '2026-01-15',
    fechaUltimaActuacion: '2026-03-28',
    montoDeuda: 485200.50,
    folios: 47,
    tieneAlarma: true,
    fechaVencimientoAlarma: '2026-04-20',
    cct: 'CCT 547/03',
  },
  {
    id: 'exp-002',
    numeroExpediente: 'SIGEF-2026-00002',
    caratula: 'SMATA c/ AUTOMOTORES PATAGONIA S.R.L. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'AUTOMOTORES PATAGONIA S.R.L.',
      cuit: '30-68765432-1',
      domicilio: 'Ruta 3 Km 45, Esteban Echeverría, Pcia. Bs. As.',
      actividadPrincipal: 'Concesionario Automotor',
    },
    requirente: mockRequirentes[2],
    inspector: mockInspectores[1],
    estado: 'B_INSTRUCCION',
    fechaInicio: '2026-02-03',
    fechaUltimaActuacion: '2026-04-05',
    montoDeuda: undefined,
    folios: 18,
    tieneAlarma: false,
    cct: 'CCT 40/89',
  },
  {
    id: 'exp-003',
    numeroExpediente: 'SIGEF-2026-00003',
    caratula: 'OSDE c/ CLÍNICA INTEGRAL DEL NORTE S.A. s/ INSPECCIÓN OBRA SOCIAL',
    empresa: {
      razonSocial: 'CLÍNICA INTEGRAL DEL NORTE S.A.',
      cuit: '30-72345678-9',
      domicilio: 'Av. Santa Fe 3456, C.A.B.A.',
      actividadPrincipal: 'Servicios de Salud',
    },
    requirente: mockRequirentes[1],
    inspector: mockInspectores[0],
    estado: 'C2_IMPUGNACION',
    fechaInicio: '2025-11-10',
    fechaUltimaActuacion: '2026-04-01',
    montoDeuda: 1250800.00,
    folios: 93,
    tieneAlarma: true,
    fechaVencimientoAlarma: '2026-04-15',
    cct: 'CCT 122/75',
  },
  {
    id: 'exp-004',
    numeroExpediente: 'SIGEF-2026-00004',
    caratula: 'UPCN c/ CONSTRUCTORA FEDERAL S.A. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'CONSTRUCTORA FEDERAL S.A.',
      cuit: '30-65432198-7',
      domicilio: 'Av. Juan B. Justo 789, C.A.B.A.',
      actividadPrincipal: 'Construcción',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[2],
    estado: 'D_COBRO_CIERRE',
    fechaInicio: '2025-09-01',
    fechaUltimaActuacion: '2026-03-15',
    montoDeuda: 320500.75,
    folios: 128,
    tieneAlarma: false,
    cct: 'CCT 76/75',
  },
  {
    id: 'exp-005',
    numeroExpediente: 'SIGEF-2026-00005',
    caratula: 'SMATA c/ REPUESTOS OMEGA S.R.L. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'REPUESTOS OMEGA S.R.L.',
      cuit: '30-70123456-3',
      domicilio: 'Calle 25 de Mayo 456, Quilmes, Pcia. Bs. As.',
      actividadPrincipal: 'Comercio Repuestos Automotor',
    },
    requirente: mockRequirentes[2],
    inspector: mockInspectores[1],
    estado: 'A_INICIO',
    fechaInicio: '2026-04-08',
    fechaUltimaActuacion: '2026-04-08',
    folios: 3,
    tieneAlarma: false,
    cct: 'CCT 40/89',
  },
  {
    id: 'exp-006',
    numeroExpediente: 'SIGEF-2025-00089',
    caratula: 'UPCN c/ LOGÍSTICA TOTAL S.A. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'LOGÍSTICA TOTAL S.A.',
      cuit: '30-69876543-5',
      domicilio: 'Av. Rivadavia 8900, C.A.B.A.',
      actividadPrincipal: 'Logística y Transporte',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'FINALIZADO',
    fechaInicio: '2025-05-20',
    fechaUltimaActuacion: '2026-02-28',
    montoDeuda: 0,
    folios: 215,
    tieneAlarma: false,
    cct: 'CCT 547/03',
  },
  {
    id: 'exp-007',
    numeroExpediente: 'SIGEF-2026-00006',
    caratula: 'OSDE c/ FARMACIA CENTRAL DEL OESTE S.A. s/ INSPECCIÓN OBRA SOCIAL',
    empresa: {
      razonSocial: 'FARMACIA CENTRAL DEL OESTE S.A.',
      cuit: '30-73456789-0',
      domicilio: 'Av. Gaona 2345, C.A.B.A.',
      actividadPrincipal: 'Farmacia',
    },
    requirente: mockRequirentes[1],
    inspector: mockInspectores[2],
    estado: 'C1_DEUDA_CONSENTIDA',
    fechaInicio: '2026-01-22',
    fechaUltimaActuacion: '2026-04-10',
    montoDeuda: 89340.00,
    folios: 38,
    tieneAlarma: true,
    fechaVencimientoAlarma: '2026-04-18',
    cct: 'CCT 486/07',
  },
];
