import { Expediente, Requirente, Usuario } from './types';

export const mockRequirentes: Requirente[] = [
  {
    id: 'req-seca',
    nombre: 'Sindicato Empleados del Caucho y Afines (SECA)',
    tipo: 'SINDICATO',
    cuit: '30-67898215-2',
    domicilio: 'Tomás Antonio Valle 1281 - C.A.B.A.',
    personeria: 'Personería Gremial Nº 295',
  },
  {
    id: 'req-ospeca',
    nombre: 'Obra Social del Personal del Caucho y Afines (OS.PE.CA)',
    tipo: 'OBRA_SOCIAL',
    cuit: '30-53246077-4',
    domicilio: 'Tomás Antonio Valle 1281 - C.A.B.A.',
  },
];

export const mockInspectores: Usuario[] = [
  { id: 'usr-1', nombre: 'Ignacio', apellido: 'Pecorelli', rol: 'INSPECTOR', email: 'i.pecorelli@sigef.gob.ar', titulo: 'Dr.' },
];

export const mockExpedientes: Expediente[] = [
  {
    id: 'exp-001',
    numeroExpediente: 'SIGEF-2026-00001',
    caratula: 'SECA c/ TECNOLOGÍAS DEL SUR S.A. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'TECNOLOGÍAS DEL SUR S.A.',
      cuit: '30-71234567-8',
      domicilio: 'Av. Corrientes 1234, C.A.B.A.',
      actividadPrincipal: 'Fabricación de Neumáticos',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'DEUDA_DETERMINADA',
    fechaInicio: '2026-01-15',
    fechaUltimaActuacion: '2026-03-28',
    montoDeuda: 485200.50,
    folios: 47,
    tieneAlarma: true,
    fechaVencimientoAlarma: '2026-04-20',
    cct: 'CCT 402/05 (Neumáticos)',
  },
  {
    id: 'exp-002',
    numeroExpediente: 'SIGEF-2026-00002',
    caratula: 'SECA c/ CAUCHO INDUSTRIAL PATAGONIA S.R.L. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'CAUCHO INDUSTRIAL PATAGONIA S.R.L.',
      cuit: '30-68765432-1',
      domicilio: 'Ruta 3 Km 45, Esteban Echeverría, Pcia. Bs. As.',
      actividadPrincipal: 'Industria del Caucho',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'EN_INSTRUCCION',
    fechaInicio: '2026-02-03',
    fechaUltimaActuacion: '2026-04-05',
    folios: 18,
    tieneAlarma: false,
    cct: 'CCT 375/04 (Industria del Caucho)',
  },
  {
    id: 'exp-003',
    numeroExpediente: 'SIGEF-2026-00003',
    caratula: 'OS.PE.CA c/ CLÍNICA INTEGRAL DEL NORTE S.A. s/ INSPECCIÓN OBRA SOCIAL',
    empresa: {
      razonSocial: 'CLÍNICA INTEGRAL DEL NORTE S.A.',
      cuit: '30-72345678-9',
      domicilio: 'Av. Santa Fe 3456, C.A.B.A.',
      actividadPrincipal: 'Servicios de Salud',
    },
    requirente: mockRequirentes[1],
    inspector: mockInspectores[0],
    estado: 'CON_IMPUGNACION',
    fechaInicio: '2025-11-10',
    fechaUltimaActuacion: '2026-04-01',
    montoDeuda: 1250800.00,
    folios: 93,
    tieneAlarma: true,
    fechaVencimientoAlarma: '2026-04-18',
    cct: 'CCT 402/05 (Neumáticos)',
  },
  {
    id: 'exp-004',
    numeroExpediente: 'SIGEF-2026-00004',
    caratula: 'SECA c/ CONSTRUCTORA FEDERAL S.A. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'CONSTRUCTORA FEDERAL S.A.',
      cuit: '30-65432198-7',
      domicilio: 'Av. Juan B. Justo 789, C.A.B.A.',
      actividadPrincipal: 'Industria del Caucho',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'EN_EJECUCION',
    fechaInicio: '2025-09-01',
    fechaUltimaActuacion: '2026-03-15',
    montoDeuda: 320500.75,
    folios: 128,
    tieneAlarma: false,
    cct: 'CCT 375/04 (Industria del Caucho)',
  },
  {
    id: 'exp-005',
    numeroExpediente: 'SIGEF-2026-00005',
    caratula: 'SECA c/ REPUESTOS OMEGA S.R.L. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'REPUESTOS OMEGA S.R.L.',
      cuit: '30-70123456-3',
      domicilio: 'Calle 25 de Mayo 456, Quilmes, Pcia. Bs. As.',
      actividadPrincipal: 'Fabricación de Neumáticos',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'INICIO',
    fechaInicio: '2026-04-08',
    fechaUltimaActuacion: '2026-04-08',
    folios: 1,
    tieneAlarma: false,
    cct: 'CCT 402/05 (Neumáticos)',
  },
  {
    id: 'exp-006',
    numeroExpediente: 'SIGEF-2025-00089',
    caratula: 'SECA c/ LOGÍSTICA TOTAL S.A. s/ INSPECCIÓN GREMIAL',
    empresa: {
      razonSocial: 'LOGÍSTICA TOTAL S.A.',
      cuit: '30-69876543-5',
      domicilio: 'Av. Rivadavia 8900, C.A.B.A.',
      actividadPrincipal: 'Industria del Caucho',
    },
    requirente: mockRequirentes[0],
    inspector: mockInspectores[0],
    estado: 'FINALIZADO',
    fechaInicio: '2025-05-20',
    fechaUltimaActuacion: '2026-02-28',
    montoDeuda: 0,
    folios: 215,
    tieneAlarma: false,
    cct: 'CCT 375/04 (Industria del Caucho)',
  },
  {
    id: 'exp-007',
    numeroExpediente: 'SIGEF-2026-00006',
    caratula: 'OS.PE.CA c/ FARMACIA CENTRAL DEL OESTE S.A. s/ INSPECCIÓN OBRA SOCIAL',
    empresa: {
      razonSocial: 'FARMACIA CENTRAL DEL OESTE S.A.',
      cuit: '30-73456789-0',
      domicilio: 'Av. Gaona 2345, C.A.B.A.',
      actividadPrincipal: 'Farmacia',
    },
    requirente: mockRequirentes[1],
    inspector: mockInspectores[0],
    estado: 'CONSENTIDA',
    fechaInicio: '2026-01-22',
    fechaUltimaActuacion: '2026-04-10',
    montoDeuda: 89340.00,
    folios: 38,
    tieneAlarma: true,
    fechaVencimientoAlarma: '2026-04-25',
    cct: 'CCT 402/05 (Neumáticos)',
  },
];
